config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
  resources :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'sessions',to: 'sessions#new'
  

  resources :users, only:[:new, :create]
  get 'signup', to: 'users#new'
  
  #get 'tasks/index'
  #get 'tasks/new'
  
  #delete 'tasks/:id', to: 'tasks#destroy'
  resources :tasks

  #get 'delete', to: 'tasks#destroy'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tasks
  validates :username, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Login Successful"
      redirect_to :tasks
    else
      flash.alert = "Login failed"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out, Goodbye"
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :confirm_login
  before_action :load_task, :confirm_owner, except: [:index, :new, :create]
  
  def index
    @tasks = current_user.tasks.all
  end

  def new
    @task = Task.new
  end

  def show
    #@task = Task.find(params[:id])
  end

  def edit
    #@task = Task.find(params[:id])

  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path
    else 
      render 'new'
    end
  end

  def update
    #@task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else 
      render 'edit'
    end
  end
  
  def destroy
    #@task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def confirm_login
    unless current_user
      redirect_to root_path, alert: "You need to login first"
    end
  end

  def load_task 
    @task = Task.find(params[:id])
  end

  def confirm_owner
    #@task = Task.find(params[:id])
    if @task && current_user != @task.user
      redirect_to tasks_path, alert: "You do not have permission to view this"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        User.find(session[:user_id]) if session[:user_id]
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_error_list.html.erb
<% if object.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase%> from being saved:</h2>

      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <p style="color: green"><%= notice %></p>
    <p style="color: red"><%= alert %></p>
    <% if current_user %>
    Welcome, <%= current_user.username %>
    <%= link_to 'Log Out', :logout, class: 'btn' %>
    <% else %>
    <%= link_to 'Log In', :login, class: 'btn' %>
    <%= link_to 'Sign Up', :signup, class: 'btn'%>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_error.html.erb
<ul class ="error-list">
    <% @task.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>

</ul>

<% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
    <%= render 'error_list', object: @task %>
    <%= f.label "Title:" %><br>
    <%= f.text_field :title %><br>

    <%= f.label "Details:" %><br>
    <%= f.text_area :details %><br>
    <%= f.label "Completed?" %>
    <%= f.check_box :completed %><br>


    <%= f.submit("Create", class: "btn") %>


<% end %> 

app/views/tasks/edit.html.erb
<h1> Edit Task </h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<p>Tasks go here:</p>

<ul>
   
    <% @tasks.each do |t|%>
    <li><%= link_to t.title, task_path(t) %></li>
    Completed: <%=  t.completed %>
    
    <%end%>
     
</ul>

<%= link_to 'New Task', new_task_path, class: "btn"%>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h3><%= @task.title %></h3>
<p><em><%= @task.details %></em></p>
<%= link_to 'Edit', edit_task_path(@task) %><br>
<%= button_to 'Delete', task_path(@task), method: :delete %><br>
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= render 'error_list', object: user%>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit("Signup", class: "btn") %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>Dont mess it up this time</p>

<%= link_to 'Look at your tasks', tasks_path, class: 'btn'%>